version: '3'

services:
  oracle-db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database/scripts:/scripts
    restart: always

#  app:
#    build:
#      context: .
#      dockerfile: ./app/Dockerfile
#    ports:
#      - '8080:8080'
#    depends_on:
#      - database
#    restart: always

volumes:
  oracle-data:
